const canvas=document.getElementById("network-canvas"),ctx=canvas.getContext("2d"),wrap=document.querySelector(".canvas-wrap"),dialog=document.getElementById("node-dialog");
const nodeData=[
{id:"yext",label:"YEXT",x:.18,y:.24,tag:"CURRENT ROLE",title:"Technical Partner Manager",copy:"I work between product, engineering, sales, and external platforms to turn ecosystem complexity into dependable integrations.",metric:"PRODUCT · PARTNERSHIPS · TECHNICAL SYSTEMS"},
{id:"platforms",label:"PLATFORMS",x:.73,y:.18,tag:"INTEGRATION STRATEGY",title:"Connecting major platforms",copy:"I lead technical partner relationships from early alignment and requirements through delivery, launch, and ongoing operations.",metric:"ALIGN → BUILD → LAUNCH → GROW"},
{id:"health",label:"HEALTHCARE",x:.82,y:.60,tag:"DATA MODELING",title:"Untangling provider identity",copy:"Healthcare data is rarely simple. I help redesign how providers and organizations map across interconnected systems.",metric:"ENTITIES · IDENTITY · PUBLISHER ECOSYSTEMS"},
{id:"systems",label:"SYSTEMS",x:.55,y:.79,tag:"PLATFORM RELIABILITY",title:"Making failures visible",copy:"I build monitoring and operational systems that turn integration failures into clear, actionable signals.",metric:"DATA · MONITORING · OPERATIONS"},
{id:"amazon",label:"AMAZON",x:.17,y:.73,tag:"EARLY EXPERIENCE",title:"Learning systems at scale",copy:"At Amazon, I worked across engineering and operations to improve data workflows and automate repetitive processes.",metric:"AUTOMATION · DATA QUALITY · SCALE"},
{id:"scaffold",label:"SCAFFOLD",x:.42,y:.43,tag:"SIDE PROJECT",title:"Something you can click",copy:"A working side project and proof that I enjoy moving from a vague idea to a real, usable product.",metric:"DESIGN · CODE · SHIP",link:"/scaffold/"}
];
let width=0,height=0,dpr=1,signal={x:0,y:0,vx:1,vy:0},trail=[],last=0,mapActive=false,cooldown=0;
const visited=new Set(),keys=new Set();
function resize(){const r=wrap.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);width=r.width;height=r.height;canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);if(!signal.x){signal.x=width*.5;signal.y=height*.58}}
new ResizeObserver(resize).observe(wrap);resize();
new IntersectionObserver(([e])=>mapActive=e.isIntersecting&&e.intersectionRatio>.25,{threshold:[.25]}).observe(canvas);
function setDirection(dir){if(dir==="up"){signal.vx=0;signal.vy=-1}if(dir==="down"){signal.vx=0;signal.vy=1}if(dir==="left"){signal.vx=-1;signal.vy=0}if(dir==="right"){signal.vx=1;signal.vy=0}}
const directionKeys={ArrowUp:"up",w:"up",W:"up",ArrowDown:"down",s:"down",S:"down",ArrowLeft:"left",a:"left",A:"left",ArrowRight:"right",d:"right",D:"right"};
addEventListener("keydown",e=>{if(directionKeys[e.key]&&mapActive){e.preventDefault();setDirection(directionKeys[e.key]);keys.add(e.key)}});addEventListener("keyup",e=>keys.delete(e.key));
document.querySelectorAll("[data-direction]").forEach(b=>{b.addEventListener("pointerdown",()=>setDirection(b.dataset.direction))});
function nodePosition(n){return{x:n.x*width,y:n.y*height}}
function openNode(n){if(!n)return;visited.add(n.id);document.getElementById("visited-count").textContent=visited.size;document.getElementById("dialog-tag").textContent=n.tag;document.getElementById("dialog-title").textContent=n.title;document.getElementById("dialog-copy").textContent=n.copy;document.getElementById("dialog-metric").textContent=n.metric;const a=document.getElementById("dialog-link");if(n.link){a.href=n.link;a.hidden=false}else a.hidden=true;if(!dialog.open)dialog.showModal();cooldown=1200}
document.querySelector(".dialog-close").onclick=()=>dialog.close();dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()});
canvas.addEventListener("click",e=>{const r=canvas.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;let nearest=null,dist=55;nodeData.forEach(n=>{const p=nodePosition(n),d=Math.hypot(mx-p.x,my-p.y);if(d<dist){dist=d;nearest=n}});if(nearest){const p=nodePosition(nearest);signal.x=p.x;signal.y=p.y;trail.unshift({x:p.x,y:p.y});openNode(nearest)}});
function roundedRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function drawGrid(){ctx.strokeStyle="rgba(255,255,255,.045)";ctx.lineWidth=1;for(let x=0;x<width;x+=42){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,height);ctx.stroke()}for(let y=0;y<height;y+=42){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(width,y);ctx.stroke()}}
function drawConnections(){const pairs=[[0,1],[0,2],[0,4],[1,3],[2,3],[3,5],[4,5]];ctx.lineWidth=1;pairs.forEach(([a,b])=>{const p=nodePosition(nodeData[a]),q=nodePosition(nodeData[b]),active=visited.has(nodeData[a].id)&&visited.has(nodeData[b].id);ctx.strokeStyle=active?"rgba(200,255,61,.55)":"rgba(91,224,255,.12)";ctx.setLineDash([4,7]);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()});ctx.setLineDash([])}
function drawNodes(t){nodeData.forEach(n=>{const p=nodePosition(n),active=visited.has(n.id),pulse=3+Math.sin(t/450+n.x*8)*2;ctx.fillStyle=active?"rgba(200,255,61,.12)":"rgba(91,224,255,.07)";ctx.beginPath();ctx.arc(p.x,p.y,28+pulse,0,Math.PI*2);ctx.fill();ctx.strokeStyle=active?"#c8ff3d":"#5be0ff";ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,12,0,Math.PI*2);ctx.stroke();ctx.fillStyle=active?"#c8ff3d":"#5be0ff";ctx.beginPath();ctx.arc(p.x,p.y,4,0,Math.PI*2);ctx.fill();ctx.font="500 10px 'DM Mono'";ctx.textAlign="center";ctx.fillStyle=active?"#c8ff3d":"rgba(255,255,255,.72)";ctx.fillText(n.label,p.x,p.y+47)})}
function update(dt){const speed=Math.min(width,height)*.00017*dt;signal.x+=signal.vx*speed;signal.y+=signal.vy*speed;if(signal.x<0)signal.x=width;if(signal.x>width)signal.x=0;if(signal.y<0)signal.y=height;if(signal.y>height)signal.y=0;trail.unshift({x:signal.x,y:signal.y});if(trail.length>28)trail.pop();cooldown=Math.max(0,cooldown-dt);if(!cooldown&&!dialog.open){for(const n of nodeData){const p=nodePosition(n);if(Math.hypot(signal.x-p.x,signal.y-p.y)<19){openNode(n);break}}}}
function drawSignal(){trail.forEach((p,i)=>{const alpha=(1-i/trail.length)*.75,size=Math.max(2,7-i*.18);ctx.fillStyle=`rgba(200,255,61,${alpha})`;ctx.beginPath();ctx.arc(p.x,p.y,size,0,Math.PI*2);ctx.fill()});ctx.shadowColor="#c8ff3d";ctx.shadowBlur=18;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(signal.x,signal.y,6,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}
function frame(t){const dt=Math.min(t-last||16,32);last=t;ctx.clearRect(0,0,width,height);drawGrid();drawConnections();drawNodes(t);update(dt);drawSignal();requestAnimationFrame(frame)}requestAnimationFrame(frame);