const canvas=document.getElementById("network-canvas"),ctx=canvas.getContext("2d"),wrap=document.querySelector(".canvas-wrap"),dialog=document.getElementById("node-dialog"),toast=document.getElementById("game-toast"),game=document.querySelector(".game");
const COLS=18,ROWS=11;
const linkedInLink=document.createElement("a");linkedInLink.id="dialog-linkedin";linkedInLink.href="https://www.linkedin.com/in/brettgoodman11";linkedInLink.textContent="LinkedIn";linkedInLink.hidden=true;linkedInLink.style.cssText="display:inline-block;margin-top:15px;margin-left:8px;background:#111118;color:#fff;padding:10px 15px;border-radius:30px;text-decoration:none;font:10px 'DM Mono'";dialog.append(linkedInLink);
const nodes=[
{id:"unc",label:"UNC Â· 20â23",gx:3,gy:8,color:"#7BAFD4",ink:"#13294B",tag:"2020 â DECEMBER 2023",title:"UNC Kenan-Flagler",copy:"University of North Carolina at Chapel Hill. B.S. in Business Administration + Data Science."},
{id:"crowded",label:"CROWDED Â· 22",gx:15,gy:8,color:"#246BFD",ink:"#FFFFFF",tag:"2022 Â· TEL AVIV",title:"Product Management Intern",copy:"As an intern, built a scraper that generated 10,000+ leads and booked 50+ demos for a Tel Aviv fintech."},
{id:"amazon",label:"AMAZON Â· 23",gx:3,gy:2,color:"#FF9900",ink:"#111118",tag:"2023 Â· SEATTLE",title:"Technical Program Manager Intern",copy:"As an intern, built a deduplication tool and a new data process projected to save Amazon $2.1M and 1,700 labor hours in year one."},
{id:"curinos",label:"CURINOS Â· 24",gx:9,gy:1,color:"#6D50FF",ink:"#FFFFFF",tag:"MARCH â OCTOBER 2024",title:"Associate",copy:"Modeled $1T+ in retail deposits to help large US consumer banks make pricing, acquisition and retention calls."},
{id:"yext",label:"YEXT Â· 24â",gx:15,gy:2,color:"#FFFFFF",ink:"#111118",tag:"OCTOBER 2024 â NOW Â· NEW YORK",title:"Technical Partner Manager",copy:"Led 65+ integrations across 45M+ listings and 200M+ reviews, from two Google launches that generated $2.8M in new ARR to a 0-to-1 Apple Maps reseller offering behind $10M+ in upsells and renewals."},
{id:"scaffold",label:"SCAFFOLDMAX Â· 26",gx:9,gy:5,color:"#C8FF45",ink:"#111118",tag:"2026 Â· SIDE PROJECT",title:"ScaffoldMaxNYC",copy:"Built a route planner for the most New York problem: crossing town under scaffolding when it rains.",link:"/scaffold/"}
];
const nodeSlots=[{x:3,y:8},{x:15,y:8},{x:3,y:2},{x:9,y:1},{x:15,y:2},{x:9,y:5}];
const hazardSlots=[{x:6,y:3},{x:12,y:3},{x:6,y:7},{x:12,y:7},{x:9,y:7},{x:2,y:5},{x:15,y:5},{x:9,y:3},{x:4,y:5},{x:14,y:9}];
let hazards=[];
let width=0,height=0,dpr=1,cell=40,offsetX=0,offsetY=0,tick=0,snake=[],dir={x:1,y:0},visited=new Set(),targetIndex=0,moves=0,won=false,pendingWin=false,toastTimer=null,confetti=[];
const directions={ArrowUp:{x:0,y:-1},w:{x:0,y:-1},W:{x:0,y:-1},ArrowDown:{x:0,y:1},s:{x:0,y:1},S:{x:0,y:1},ArrowLeft:{x:-1,y:0},a:{x:-1,y:0},A:{x:-1,y:0},ArrowRight:{x:1,y:0},d:{x:1,y:0},D:{x:1,y:0}};
function updateHud(){document.getElementById("node-count").textContent=nodes.length;document.getElementById("visited-count").textContent=visited.size;document.getElementById("move-count").textContent=moves;document.getElementById("target-label").textContent=won?"YOU WIN":nodes[targetIndex].label.split(" Â· ")[0]}
function shuffled(items){const copy=items.slice();for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function randomizeBoard(){const slots=shuffled(nodeSlots);nodes.forEach((n,i)=>{n.gx=slots[i].x;n.gy=slots[i].y});hazards=shuffled(hazardSlots).slice(0,5)}
function resetSnake(){snake=[{x:9,y:9},{x:8,y:9},{x:7,y:9},{x:6,y:9}];dir={x:1,y:0}}
function reset(shouldFocus=true){randomizeBoard();resetSnake();visited=new Set();targetIndex=0;moves=0;won=false;pendingWin=false;confetti=[];linkedInLink.hidden=true;dialog.classList.remove("win");if(dialog.open)dialog.close();updateHud();if(shouldFocus)canvas.focus();draw()}
function resize(){const r=wrap.getBoundingClientRect();width=r.width;height=r.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);cell=Math.min(width/(COLS+1),height/(ROWS+1));offsetX=(width-cell*COLS)/2;offsetY=(height-cell*ROWS)/2;draw()}
new ResizeObserver(resize).observe(wrap);
function pt(gx,gy){return{x:offsetX+(gx+.5)*cell,y:offsetY+(gy+.5)*cell}}
function showToast(text){toast.textContent=text;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),1100)}
function crash(){game.classList.remove("crash");void game.offsetWidth;game.classList.add("crash");setTimeout(()=>game.classList.remove("crash"),650)}
function openNode(n){document.getElementById("dialog-tag").textContent=n.tag;document.getElementById("dialog-title").textContent=n.title;document.getElementById("dialog-copy").textContent=n.copy;const link=document.getElementById("dialog-link");link.textContent="go there â";link.hidden=!n.link;linkedInLink.hidden=true;if(n.link)link.href=n.link;if(!dialog.open)dialog.showModal()}
function celebrate(){won=true;updateHud();dialog.classList.add("win");document.getElementById("dialog-tag").textContent="6/6 FOUND";document.getElementById("dialog-title").textContent="You won!";document.getElementById("dialog-copy").textContent="Find out more about me here.";const link=document.getElementById("dialog-link");link.hidden=false;link.href="mailto:brettgoodman11@gmail.com";link.textContent="Email me";linkedInLink.hidden=false;showToast("YOU FOUND EVERYTHING!");if(!dialog.open)dialog.showModal();for(let i=0;i<260;i++)confetti.push({x:width/2,y:height/3,vx:(Math.random()-.5)*13,vy:Math.random()*-11-3,c:["#c8ff45","#ff6b4a","#76d8ff","#ffd95a","#ff9dc6"][i%5],r:Math.random()*5+2})}
function move(next){if(won)return;dir=next;const head=snake[0],newHead={x:(head.x+dir.x+COLS)%COLS,y:(head.y+dir.y+ROWS)%ROWS};moves++;if(hazards.some(h=>h.x===newHead.x&&h.y===newHead.y)||snake.some(s=>s.x===newHead.x&&s.y===newHead.y)){reset();crash();showToast("CRASH â BACK TO START");return}snake.unshift(newHead);const target=nodes[targetIndex],foundTarget=newHead.x===target.gx&&newHead.y===target.gy;if(foundTarget){visited.add(target.id);targetIndex++;showToast("FOUND: "+target.label.split(" Â· ")[0]);openNode(target);if(targetIndex===nodes.length){pendingWin=true;won=true}}else{snake.pop();const wrong=nodes.find(n=>n.gx===newHead.x&&n.gy===newHead.y&&!visited.has(n.id));if(wrong)showToast("FIND "+target.label.split(" Â· ")[0]+" FIRST")}updateHud();draw()}
addEventListener("keydown",e=>{if(!directions[e.key]||document.activeElement!==canvas)return;e.preventDefault();move(directions[e.key])});
canvas.addEventListener("mouseenter",()=>canvas.focus());
canvas.addEventListener("click",e=>{canvas.focus();const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;const node=nodes.find(n=>{const p=pt(n.gx,n.gy);return Math.hypot(x-p.x,y-p.y)<=cell*.48});if(node)openNode(node)});
document.querySelectorAll("[data-direction]").forEach(b=>b.addEventListener("click",()=>{canvas.focus();const name="Arrow"+b.dataset.direction[0].toUpperCase()+b.dataset.direction.slice(1);move(directions[name])}));
document.getElementById("reset-game").onclick=()=>reset(true);document.querySelector(".dialog-close").onclick=()=>{dialog.close();canvas.focus()};dialog.addEventListener("click",e=>{if(e.target===dialog){dialog.close();canvas.focus()}});
dialog.addEventListener("close",()=>{if(pendingWin){pendingWin=false;celebrate()}});
function grid(){ctx.fillStyle="#0d0e17";ctx.fillRect(0,0,width,height);ctx.strokeStyle="rgba(255,255,255,.06)";ctx.lineWidth=1;for(let x=0;x<=COLS;x++){const px=offsetX+x*cell;ctx.beginPath();ctx.moveTo(px,offsetY);ctx.lineTo(px,offsetY+ROWS*cell);ctx.stroke()}for(let y=0;y<=ROWS;y++){const py=offsetY+y*cell;ctx.beginPath();ctx.moveTo(offsetX,py);ctx.lineTo(offsetX+COLS*cell,py);ctx.stroke()}}
function drawHazards(){hazards.forEach(h=>{const p=pt(h.x,h.y),r=cell*.24;ctx.fillStyle="#351923";ctx.fillRect(p.x-r,p.y-r,r*2,r*2);ctx.strokeStyle="#ff6b4a";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(p.x-r*.55,p.y-r*.55);ctx.lineTo(p.x+r*.55,p.y+r*.55);ctx.moveTo(p.x+r*.55,p.y-r*.55);ctx.lineTo(p.x-r*.55,p.y+r*.55);ctx.stroke()})}
function drawNodes(){nodes.forEach((n,i)=>{const p=pt(n.gx,n.gy),found=visited.has(n.id),target=i===targetIndex&&!won,pulse=target?5+Math.sin(tick*3)*3:0;ctx.beginPath();ctx.arc(p.x,p.y,cell*.24+pulse,0,Math.PI*2);ctx.fillStyle=n.color;ctx.fill();ctx.lineWidth=target?5:found?3:2;ctx.strokeStyle=target?"#c8ff45":found?"#76d8ff":"#fff";ctx.stroke();ctx.fillStyle=n.ink;ctx.font=`600 ${Math.max(9,cell*.22)}px 'DM Mono'`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(String(i+1),p.x,p.y);ctx.fillStyle=n.color;ctx.font=`500 ${Math.max(8,cell*.2)}px 'DM Mono'`;ctx.fillText(n.label,p.x,p.y+cell*.62)})}
function drawSnake(){snake.slice().reverse().forEach((s,ri)=>{const original=snake.length-1-ri,p=pt(s.x,s.y),head=original===0,size=cell*(head?.34:.28);ctx.fillStyle=head?"#c8ff45":"#76d8ff";ctx.strokeStyle="#111118";ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(p.x-size,p.y-size,size*2,size*2,Math.max(5,size*.55));ctx.fill();ctx.stroke();if(head){const ex=dir.y?cell*.11:dir.x*cell*.13,ey=dir.x?cell*.11:dir.y*cell*.13;ctx.fillStyle="#111118";ctx.beginPath();ctx.arc(p.x+ex-dir.y*cell*.1,p.y+ey-dir.x*cell*.1,2.4,0,Math.PI*2);ctx.arc(p.x+ex+dir.y*cell*.1,p.y+ey+dir.x*cell*.1,2.4,0,Math.PI*2);ctx.fill()}})}
function drawConfetti(){confetti.forEach(c=>{c.x+=c.vx;c.y+=c.vy;c.vy+=.13;ctx.fillStyle=c.c;ctx.fillRect(c.x,c.y,c.r,c.r)});confetti=confetti.filter(c=>c.y<height+20)}
function draw(){grid();drawHazards();drawNodes();drawSnake();drawConfetti()}
function animate(t){tick=t/500;draw();requestAnimationFrame(animate)}
reset(false);resize();requestAnimationFrame(animate);
